### ISSUE TITLE
Setup Containers to mount NFS instead HostPath

### ISSUE THREAD

**Issue by antonionappi88** [oracle/weblogic-kubernetes-operator#100]
Hello,
I tried to run the weblogic domain using as shared volume a NFS volume. So the containers where attaching a NFS volume instead of using HostPath. [Here](https://db-blog.web.cern.ch/blog/antonio-nappi/2018-02-setup-nfs-storage-oracle-cloud-infrastructure-using-linux-storage) there is how I setup a NFS server in OCI. On the NFS server I created a shared volume under `/shares/kube-nfs`. 

To let it to work I had to modify the `persistent-volume-template.yaml` from :

```yaml
apiVersion: v1                          
kind: PersistentVolume                  
metadata:                               
  name: %PERSISTENT_VOLUME%             
  labels:                               
    weblogic.domainUID: %DOMAIN_UID%    
spec:                                   
  storageClassName: %STORAGE_CLASS_NAME%
  capacity:                             
    storage: %PERSISTENT_VOLUME_SIZE%   
  accessModes:                          
    - ReadWriteMany                     
  persistentVolumeReclaimPolicy: Retain 
  hostPath:                             
    path: "%PERSISTENT_VOLUME_PATH%"    
```

 to :

``` yaml
apiVersion: v1                          
kind: PersistentVolume                  
metadata:                               
  name: %PERSISTENT_VOLUME%             
  labels:                               
    weblogic.domainUID: %DOMAIN_UID%    
spec:                                   
  storageClassName: %STORAGE_CLASS_NAME%
  capacity:                             
    storage: %PERSISTENT_VOLUME_SIZE%   
  accessModes:                          
    - ReadWriteMany                     
  persistentVolumeReclaimPolicy: Retain 
  nfs:                                  
     server: NFS_SERVER_IP               
     path: "%PERSISTENT_VOLUME_PATH%"   
```
And in the create-domain-job-inputs.yaml I had to set `/shares/kube-nfs` as persistencePath.

Hope it helps.
