### ISSUE TITLE
create-domain.sh gives [ERROR] Create domain sample-domain1 failed.

### ISSUE THREAD

**Issue by creativefre** [oracle/weblogic-kubernetes-operator#1028]
Hello, I get the following error when I run the create-domain.sh

Kubernetes is setup correctly and the images are pulled.
I'm following the QUICK START guide from the documentation. Every command before this executed successfully.

When I try to create the domain with the following command,

`sudo ./create-domain.sh -i my-inputs.yaml -o /home/oracle/WERK -u weblogic -p welcome1 -e`

I get the following output.
```bash
oracle@lnx-stage01:~/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image$ sudo ./create-domain.sh -i my-inputs.yaml -o /home/oracle/WERK -u weblogic -p welcome1 -e
Input parameters being used
export version="create-weblogic-sample-domain-inputs-v1"
export adminPort="7001"
export adminServerName="admin-server"
export domainUID="sample-domain1"
export serverStartPolicy="IF_NEEDED"
export clusterName="cluster-1"
export configuredManagedServerCount="5"
export initialManagedServerReplicas="3"
export managedServerNameBase="managed-server"
export managedServerPort="8001"
export productionModeEnabled="true"
export imagePullPolicy="IfNotPresent"
export weblogicCredentialsSecretName="sample-domain1-weblogic-credentials"
export includeServerOutInPodLog="true"
export logHomeOnPV="false"
export logHome="/shared/logs/domain1"
export t3ChannelPort="30012"
export exposeAdminT3Channel="false"
export adminNodePort="30701"
export exposeAdminNodePort="false"
export namespace="sample-domain1-ns"
javaOptions=-Dweblogic.StdoutDebugEnabled=false
export persistentVolumeClaimName="sample-domain1-weblogic-sample-pvc"
export domainPVMountPath="/shared"
export domainHomeImageBase="store/oracle/weblogic:12.2.1.3"
export domainHomeImageBuildPath="./docker-images/OracleWebLogic/samples/12213-domain-home-in-image"

Cloning into './docker-images'...
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 10023 (delta 24), reused 31 (delta 13), pack-reused 9966
Receiving objects: 100% (10023/10023), 8.88 MiB | 10.55 MiB/s, done.
Resolving deltas: 100% (5819/5819), done.
Generating /home/oracle/WERK/weblogic-domains/sample-domain1/domain.properties
Generating /home/oracle/WERK/weblogic-domains/sample-domain1/domain.yaml
Checking to see if the secret sample-domain1-weblogic-credentials exists in namespace sample-domain1-ns
Context for docker build is /home/oracle/weblogic-kubernetes-operator/kubernetes/samples/scripts/create-weblogic-domain/domain-home-in-image/docker-images/OracleWebLogic/samples/12213-domain-home-in-image
A properties file with variable definitions should be supplied.
[ERROR] Create domain sample-domain1 failed.
```
I can't seem to figure out what the problem is.
This is the content of my-inputs.yaml
```yaml
# Copyright 2018, 2019, Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

# The version of this inputs file.  Do not modify.
version: create-weblogic-sample-domain-inputs-v1

# Port number for admin server
adminPort: 7001

# Name of the Admin Server
adminServerName: admin-server

# Unique ID identifying a domain.
# This ID must not contain an underscope ("_"), and must be lowercase and unique across all domains
# in a Kubernetes cluster.
domainUID: sample-domain1

# Determines which WebLogic Servers the operator will start up
# Legal values are "NEVER", "IF_NEEDED", or "ADMIN_ONLY"
serverStartPolicy: IF_NEEDED

# Cluster name
clusterName: cluster-1

# Number of managed servers to generate for the domain
configuredManagedServerCount: 5

# Number of managed servers to initially start for the domain
initialManagedServerReplicas: 3

# Base string used to generate managed server names
managedServerNameBase: managed-server

# Port number for each managed server
managedServerPort: 8001

# Boolean indicating if production mode is enabled for the domain
productionModeEnabled: true

# WebLogic Server Docker image that the operator uses to start the domain.
#
# The create domain scripts generate a WebLogic Server Docker image with a domain home in it.
# By default, the scripts tag the generated WebLogic server Docker image as either
# `domain-home-in-image` or `domain-home-in-image-wdt` based on the `domainHomeImageBuildPath`
# property, and use it to set the `image` element in the generated domain YAML file.
#
# If this property is set, the create domain scripts will use the value specified, instead of the
# default value, to tag the generated image and set the `image` in the domain YAML file.
#
# A unique value is required for each domain that is created using the scripts.
#
# If you are running the sample scripts from a machine that is remote to the Kubernetes cluster where
# the domain is going to be running, you need to set this property to the image name that is intended
# to be used in a registry local to that Kubernetes cluster. You also need to push the `image` to
# that registry before starting the domain using the `kubectl create -f` or `kubectl apply -f` command.
# See README.md for more help.
#image:

# Image pull policy
# Legal values are "IfNotPresent", "Always", or "Never"
imagePullPolicy: IfNotPresent

# Name of the Kubernetes secret to access the Docker Store to pull the WebLogic Server Docker image
# The presence of the secret will be validated when this parameter is enabled.
#imagePullSecretName:

# Name of the Kubernetes secret for the Admin Server's username and password
# The name must be lowercase.
# If not specified, the value is derived from the domainUID as <domainUID>-weblogic-credentials
weblogicCredentialsSecretName: sample-domain1-weblogic-credentials

# Whether to include server .out to the pod's stdout.
# The default is true.
includeServerOutInPodLog: true

# Specifies whether the log home is stored on the persistent volume.
# If set to true, then you must specify the 'logHome', 'persistentVolumeClaimName'
# and 'domainPVMountPath' properties.
# The default is false.
logHomeOnPV: false

# The in-pod location for domain log, server logs, server out, and node manager log files
# If not specified, the value is derived from the domainUID as /shared/logs/<domainUID>
# This parameter is required if 'logHomeOnPV' is true.
# Otherwise, it is ignored.
logHome: /shared/logs/domain1

# Port for the T3Channel of the NetworkAccessPoint
t3ChannelPort: 30012

# Public address for T3Channel of the NetworkAccessPoint.  This value should be set to the
# kubernetes server address, which you can get by running "kubectl cluster-info".  If this
# value is not set to that address, WLST will not be able to connect from outside the
# kubernetes cluster.
#t3PublicAddress:

# Boolean to indicate if the channel should be exposed as a service
exposeAdminT3Channel: false

# NodePort to expose for the admin server
adminNodePort: 30701

# Boolean to indicate if the adminNodePort will be exposed
exposeAdminNodePort: false

# Name of the domain namespace
namespace: sample-domain1-ns

# Java Option for WebLogic Server
javaOptions: -Dweblogic.StdoutDebugEnabled=false

# Name of the persistent volume claim
# If not specified, the value is derived from the domainUID as <domainUID>-weblogic-sample-pvc
# This parameter is required if 'logHomeOnPV' is true.
# Otherwise, it is ignored.
persistentVolumeClaimName: sample-domain1-weblogic-sample-pvc

# Mount path of the domain persistent volume.
# This parameter is required if 'logHomeOnPV' is true.
# Otherwise, it is ignored.
domainPVMountPath: /shared

# Base WebLogic binary image used to build the WebLogic domain image
# The operator requires WebLogic Server 12.2.1.3.0 with patch 29135930 applied.
# The existing WebLogic Docker image, `store/oracle/weblogic:12.2.1.3`, was updated on January 17, 2019,
# and has all the necessary patches applied; a `docker pull` is required if you already have this image.
# Refer to [WebLogic Docker images](../../../../../site/weblogic-docker-images.md) for details on how
# to obtain or create the image.
# See README.md for more help.
domainHomeImageBase: store/oracle/weblogic:12.2.1.3

# Location of the WebLogic "domain home in image" Docker image sample in the
# `https://github.com/oracle/docker-images.git` project.
# If not specified, use "./docker-images/OracleWebLogic/samples/12213-domain-home-in-image".
# Another possible value is "./docker-images/OracleWebLogic/samples/12213-domain-home-in-image-wdt",
# which uses WDT, instead of WLST, to generate the domain configuration.
domainHomeImageBuildPath: ./docker-images/OracleWebLogic/samples/12213-domain-home-in-image
```

Any suggestions on how to solve this would be a great help!
