### ISSUE TITLE
Problem with Server Start Arguments.

### ISSUE THREAD

**Issue by antonionappi88** [oracle/weblogic-kubernetes-operator#106]
Hello,
Via console I tried to change under `Environments -> Servers -> managed-server1(2) -> Configuration tab -> Server Start subtab` the `Arguments` with something like this : 
```java
-Dfile.encoding=utf8 -Djava.net.preferIPv4Stack=true -DentityExpansionLimit=10000 -Xmx512m
```
I killed the managed server pod and let the operator restart it.
It seems that the managed server is started without these parameters even if these values are saved in the config.xml.

For example if I checked on the container with : 
```bash
cat /proc/`jps | grep Server | awk '{print $1}'`/cmdline
```
This comand print the start command of the server and the parameters are not there>
They should be also in the `startup.properties` under the nodemanager directory.(in the today call I said nodemanager.properties, sorry i confused the names).

**Comment by tbarnes-us** [comment]
Hi, 

Thanks you for filing this Issue.   I don't think the operator currently supports setting WebLogic JVM command line arguments via the WebLogic console, although I can certainly see how that might be convenient I'm not sure whether it'd be straight forward to implement.    Do you think this should be a high priority?     

Alternatively, it should be possible to set WebLogic JVM command line args via the JAVA_OPTIONS/USER_MEM_ARGS env vars in your domain custom resource yaml.    Here's a yaml snippet:

```
  serverStartup:
  # desiredState legal values are "RUNNING" or "ADMIN"
  # "RUNNING" means the listed server will be started up to "RUNNING" mode
  # "ADMIN" means the listed server will be start up to "ADMIN" mode
  - desiredState: "RUNNING"
    # the name of the server to apply these rules to
    serverName: "admin-server"
    # an (optional) list of environment variable to be set on the server
    env:
    - name: JAVA_OPTIONS
      value: "-Dweblogic.StdoutDebugEnabled=false"
    - name: USER_MEM_ARGS
      value: "-Xms64m -Xmx256m "
  # clusterStartup has the same structure as serverStartup, but it allows you to specify the name
  # of a cluster instead of an individual server.  If you use this entry, then the rules will be
  # applied to ALL servers that are members of the named clusters.
  clusterStartup:
  - desiredState: "RUNNING"
    clusterName: "cluster-1"
    replicas: 2
    env:
    - name: JAVA_OPTIONS
      value: "-Dweblogic.StdoutDebugEnabled=false"
    - name: USER_MEM_ARGS
      value: "-Xms64m -Xmx256m "
```

If you resubmit the domain yaml I'm fairly sure the operator is expected to detect the change and restart the pod(s).  

Also, if you're using the 'create-domain-job' helper script to create your domain yaml, you can specify an initial value for JAVA_OPTIONS using the 'javaOptions' tag via the create-domain-job-input yaml that feeds options into the helper script.

Hope this helps!
