### ISSUE TITLE
Error using SERVER_NAME variable in pod template when server name has underscore

### ISSUE THREAD

**Issue by anilarora** [oracle/weblogic-kubernetes-operator#1232]
Have a managed server named "ess_server1" which contains an underscore.  In my domain resource, I am using the $(SERVER_NAME) variable in the template as follows.

```
  managedServers:
  - serverName: "ess_server1"
    serverStartPolicy: "ALWAYS"
    serverPod:
      volumes:
      - name: essbase-data-storage-volume
        persistentVolumeClaim:
          claimName: essbase1-data-$(SERVER_NAME)
      volumeMounts:
      - mountPath: /u01/data
        name: essbase-data-storage-volume
```

Which results in 
```
Warning  FailedScheduling  54s (x2 over 54s)  default-scheduler  persistentvolumeclaim "essbase1-data-ess_server1" not found
```

The templating code should convert the underscores per convention as persistentVolumeClaim doesn't allow for underscore.
