### ISSUE TITLE
operator fails to deploy pods with init container

### ISSUE THREAD

**Issue by v-2vikc** [oracle/weblogic-kubernetes-operator#1430]
Error:

A security.properties file with the username and password needs to be supplied.
The file was not found in the properties directory /u01/oracle/properties

Weblogic kubernetes operator version: 2.2.1

POD deployment Yaml: 

apiVersion: "weblogic.oracle/v4"
kind: Domain
metadata:
  name: domain1
  namespace: domain1-ns
  labels:
    weblogic.resourceVersion: domain-v2
    weblogic.domainUID: domain1
spec:
  domainHome: /u01/oracle/user_projects/domains/domain1
  domainHomeInImage: true
  image: "test/:weblogic-image:latest"
  imagePullPolicy: "IfNotPresent"
  imagePullSecrets:
  - name: acrcred
  webLogicCredentialsSecret:
    name: weblogic-admin2
  includeServerOutInPodLog: true
  serverStartPolicy: "IF_NEEDED"
  serverPod:
    annotations:
      prometheus.io/scrape: "true"
    containers:
      - name: custom
        image: "test/:weblogic-image:latest"
        volumeMounts:
        - name: workdir
          mountPath: "/u01/oracle/user_projects/domains/domain1/servers/$(SERVER_NAME)/security/"
    initContainers:
    - name: wget
      image: "test/security:latest"
      env:
        - name: NEXUS_USERNAME
          valueFrom:
            secretKeyRef:
              name: nexus
              key: username
        - name: NEXUS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nexus
              key: password
        - name: URL
          value: "https://test/repository/weblogic-binaries/security/"
        - name: FILE
          value: "security.tar.gz"
      volumeMounts:
      - name: workdir
        mountPath: "/work-dir"
    volumes:
    - name: workdir
      emptyDir: {}
    shutdown:
      shutdownType: Graceful
      timeoutSeconds: 45
    imagePullSecrets:
    - name: acrcred
    restartPolicy: Never
    env:
    - name: JAVA_OPTIONS
      value: "-Dweblogic.StdoutDebugEnabled=true -Dweblogic.debug.DebugWebAppSecurity=true -Dweblogic.log.LogFileSeverity=Debug -Doracle.jdbc.fanEnabled=false"
    - name: USER_MEM_ARGS
      value: "-XX:+UseContainerSupport -Djava.security.egd=file:/dev/./urandom "
  adminServer:
    serverStartState: "RUNNING"
    adminService:
      channels:
      - channelName: default
        nodePort: 30701
      - channelName: T3Channel
  clusters:
  - clusterName: "test-cluster"
    serverStartState: "RUNNING"
    replicas: 2

**Comment by TheFrogPad** [comment]
Hi @v-2vikc  can you please describe more details of when the error you showed happens?
> A security.properties file with the username and password needs to be supplied.
> The file was not found in the properties directory /u01/oracle/properties

Can you also upload the `create-domain-inputs.yaml` used to run the domain home in image sample?

The username and password are usually supplied when creating the domain and I believe the sample scripts update or create the properties file that is used at domain creation time.

Also, you list Operator 2.2.1, have you tried this sample with latest `master` or `develop` branch? The domain in image sample defaults to cloning https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12213-domain-home-in-image and this example was updated in past couple months so it's possible something has changed.

**Comment by TheFrogPad** [comment]
Hi @v-2vikc so I just tried adding `initContainers` to a domain YAML file I had from an existing sample domain to the `adminServer` section and this worked fine:
```
  :
  :
  # adminServer is used to configure the desired behavior for starting the administration server.
  adminServer:
    # serverStartState legal values are "RUNNING" or "ADMIN"
    # "RUNNING" means the listed server will be started up to "RUNNING" mode
    # "ADMIN" means the listed server will be start up to "ADMIN" mode
    serverStartState: "RUNNING"
    adminService:
      channels:
    # The Admin Server's NodePort
       - channelName: default
         nodePort: 30701
    # Uncomment to export the T3Channel as a service
    #    - channelName: T3Channel
    serverPod:
      initContainers:
      - name: test
        image: "container-registry.oracle.com/middleware/weblogic:12.2.1.3"
        imagePullPolicy: IfNotPresent
        command: ["sh","-c","echo The URL is $URL"]
        env:
        - name: URL
          value: "http://www.example.com"
  :
  :
```
after `kubectl apply` the updated domain.yaml file and the admin server started I could see the init container results:
```
$ kubectl logs domain1-admin-server -c test -n domain1-ns
The URL is http://www.example.com
```
So more details about when you see the error would help... Thanks!
