### ISSUE TITLE
No Domain Custom resource created

### ISSUE THREAD

**Issue by karan-kapoor90** [oracle/weblogic-kubernetes-operator#183]
Raising an issue as a continuation to the thread on issue #19 
Is the domain custom resource creation yaml also supposed to be a part of the yaml file created as a part of the yaml file that created k8s resources at the end of the operator installation process? This is what mine looks like

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: operator-config-map
  namespace: weblogic-operator
data:
  serviceaccount: weblogic-operator
  targetNamespaces: "default, dev-domain, test-domain, prod-domain"
  externalOperatorCert: ##
  internalOperatorCert: ##

---
apiVersion: v1
kind: Secret
metadata:
  name: operator-secrets
  namespace: weblogic-operator
type: Opaque
data:
  externalOperatorKey: ##
  internalOperatorKey: ##

---
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: weblogic-operator
  # set the namespace that you want the operator deployed in here
  namespace: weblogic-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: weblogic-operator
    spec:
      serviceAccountName: weblogic-operator
      containers:
      - name: weblogic-operator
           image: weblogic-kubernetes-operator:karankapoor
           imagePullPolicy: IfNotPresent
        command: ["bash"]
        args: ["/operator/operator.sh"]
        #### these variables are hang overs from the oow demo, may remove them
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: OPERATOR_VERBOSE
          value: "false"
        - name: JAVA_LOGGING_LEVEL
          value: "INFO"
        #### If you wish to enable remote debugging, uncomment the following lines and set
        #### the value to the port number you want to use - note that you will also need to
        #### update the Service definition to expose this port
        - name: REMOTE_DEBUG_PORT
          value: "30999"
        volumeMounts:
        - name: operator-config-volume
          mountPath: /operator/config
        - name: operator-secrets-volume
          mountPath: /operator/secrets
          readOnly: true
        # uncomment this mount if using the ELK integration:
        - mountPath: /logs
          name: log-dir
          readOnly: false
        livenessProbe:
          exec:
            command:
              - bash
              - '/operator/livenessProbe.sh'
          initialDelaySeconds: 120
          periodSeconds: 5
      # Uncomment this container if using ELK integration:
      - name: logstash
        image: logstash:5
        args: ["-f", "/logs/logstash.conf"]
        volumeMounts:
        - mountPath: /logs
          name: log-dir
        env:
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch.default.svc.cluster.local"
        - name: ELASTICSEARCH_PORT
          value: "9200"
      volumes:
      - name: operator-config-volume
        configMap:
          name: operator-config-map
      - name: operator-secrets-volume
        secret:
          secretName: operator-secrets
      # Uncomment this volume if using ELK integration:
      - name: log-dir
        emptyDir:
          medium: Memory
      #imagePullSecrets:
      #- name: 

---
apiVersion: v1
kind: Service
metadata:
  name: external-weblogic-operator-service
  namespace: weblogic-operator
spec:
  type: NodePort
  selector:
    app: weblogic-operator
  ports:
    - port: 8081
      nodePort: 31001
      name: rest-https
    #### uncomment this port if you enable remote debugging, and make sure the value matches
    #### the one you defined above
    - port: 30999
      nodePort: 30999
      name: debug

---
apiVersion: v1
kind: Service
metadata:
  name: internal-weblogic-operator-service
  namespace: weblogic-operator
spec:
  type: ClusterIP
  selector:
    app: weblogic-operator
  ports:
    - port: 8082
      name: rest-https
```

From #19 I was looking into a possible dns issue and so I created a new busybox image and got the following

```
$ kubectl exec -ti busybox -- nslookup kubernetes.default
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'kubernetes.default'
command terminated with exit code 1
```
