### ISSUE TITLE
Create domain script did not start Admin and Managed server pods

### ISSUE THREAD

**Issue by karan-kapoor90** [oracle/weblogic-kubernetes-operator#207]
I ran the create domain script and it completed successfully as follows:
```
[kkapoor@master kubernetes]$ ./create-weblogic-domain.sh -i create-weblogic-domain-inputs.yaml -o dev-domain
Input parameters being used
export adminPort="7001"
export adminServerName="admin-server"
export domainName="dev-domain"
export domainUID="dev-domain"
export startupControl="AUTO"
export clusterName="cluster-1"
export configuredManagedServerCount="4"
export initialManagedServerReplicas="2"
export managedServerNameBase="managed-server"
export managedServerPort="8001"
export weblogicDomainStorageType="HOST_PATH"
export weblogicDomainStoragePath="/shared/dev-domain"
export weblogicDomainStorageReclaimPolicy="Retain"
export weblogicDomainStorageSize="10Gi"
export productionModeEnabled="true"
export weblogicCredentialsSecretName="dev-domain-weblogic-credentials"
export t3ChannelPort="30012"
export t3PublicAddress="10.0.2.4"
export exposeAdminT3Channel="true"
export adminNodePort="30701"
export exposeAdminNodePort="true"
export namespace="dev-domain"
export loadBalancer="TRAEFIK"
export loadBalancerWebPort="30305"
export loadBalancerDashboardPort="30315"
export javaOptions="-Dweblogic.StdoutDebugEnabled=false"

Generating dev-domain/weblogic-domains/dev-domain/weblogic-domain-persistent-volume.yaml
Generating dev-domain/weblogic-domains/dev-domain/weblogic-domain-persistent-volume-claim.yaml
Generating dev-domain/weblogic-domains/dev-domain/create-weblogic-domain-job.yaml
Generating dev-domain/weblogic-domains/dev-domain/domain-custom-resource.yaml
Generating dev-domain/weblogic-domains/dev-domain/traefik.yaml
Generating dev-domain/weblogic-domains/dev-domain/traefik-security.yaml
Checking to see if the secret dev-domain-weblogic-credentials exists in namespace dev-domain
Checking if the persistent volume dev-domain-weblogic-domain-pv exists
No resources found.
The persistent volume dev-domain-weblogic-domain-pv does not exist
Creating the persistent volume dev-domain-weblogic-domain-pv
persistentvolume "dev-domain-weblogic-domain-pv" created
Checking if the persistent volume dev-domain-weblogic-domain-pv is Available
Checking if the persistent volume claim dev-domain-weblogic-domain-pvc in namespace dev-domain exists
No resources found.
The persistent volume claim dev-domain-weblogic-domain-pvc does not exist in namespace dev-domain
Creating the persistent volume claim dev-domain-weblogic-domain-pvc
persistentvolumeclaim "dev-domain-weblogic-domain-pvc" created
Checking if the persistent volume dev-domain-weblogic-domain-pv is Bound
Checking if object type job with name domain-dev-domain-job exists
No resources found.
Creating the domain by creating the job dev-domain/weblogic-domains/dev-domain/create-weblogic-domain-job.yaml
configmap "domain-dev-domain-scripts" created
job "domain-dev-domain-job" created
Waiting for the job to complete...
status on iteration 1 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 2 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 3 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 4 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 5 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 6 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 7 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 8 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 9 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 10 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 11 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 12 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 13 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 14 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 15 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 16 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 17 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 18 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 19 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 20 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 21 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 22 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 23 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 24 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 25 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 26 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 27 of 80
pod domain-dev-domain-job-v8bgc status is Running
status on iteration 28 of 80
pod domain-dev-domain-job-v8bgc status is Completed
Setting up traefik security
clusterrole "dev-domain-cluster-1-traefik" created
clusterrolebinding "dev-domain-cluster-1-traefik" created
Checking the cluster role dev-domain-cluster-1-traefik was created
Checking the cluster role binding dev-domain-cluster-1-traefik was created
Deploying traefik
serviceaccount "dev-domain-cluster-1-traefik" created
deployment "dev-domain-cluster-1-traefik" created
configmap "dev-domain-cluster-1-traefik" created
service "dev-domain-cluster-1-traefik" created
service "dev-domain-cluster-1-traefik-dashboard" created
Checking traefik deployment
Checking the traefik service account
Checking traefik service
Creating the domain custom resource using dev-domain/weblogic-domains/dev-domain/domain-custom-resource.yaml
domain "dev-domain" created
Checking the domain custom resource was created

Domain dev-domain was created and will be started by the WebLogic Kubernetes Operator

Administration console access is available at http://10.0.2.4:30701/console
T3 access is available at t3://10.0.2.4:30012
The load balancer for cluster 'cluster-1' is available at http://10.0.2.4:30305/ (add the application path to the URL)
The load balancer dashboard for cluster 'cluster-1' is available at http://10.0.2.4:30315

The following files were generated:
  dev-domain/weblogic-domains/dev-domain/create-weblogic-domain-inputs.yaml
  dev-domain/weblogic-domains/dev-domain/weblogic-domain-persistent-volume.yaml
  dev-domain/weblogic-domains/dev-domain/weblogic-domain-persistent-volume-claim.yaml
  dev-domain/weblogic-domains/dev-domain/create-weblogic-domain-job.yaml
  dev-domain/weblogic-domains/dev-domain/domain-custom-resource.yaml
  dev-domain/weblogic-domains/dev-domain/traefik-security.yaml
  dev-domain/weblogic-domains/dev-domain/traefik.yaml

Completed
```

When I tried to open the console, nothing opened so I went into debugging what could be happening. A description of the domain does not have a Status section:
```
[kkapoor@master dev-domain]$ kubectl describe domain dev-domain -n dev-domain
Name:         dev-domain
Namespace:    dev-domain
Labels:       weblogic.domainUID=dev-domain
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"weblogic.oracle/v1","kind":"Domain","metadata":{"annotations":{},"labels":{"weblogic.domainUID":"dev-domain"},"name":"dev-domain","names...
API Version:  weblogic.oracle/v1
Kind:         Domain
Metadata:
  Cluster Name:        
  Creation Timestamp:  2018-04-25T09:50:06Z
  Resource Version:    94001
  Self Link:           /apis/weblogic.oracle/v1/namespaces/dev-domain/domains/dev-domain
  UID:                 08935147-486e-11e8-bf58-080027f9aafe
Spec:
  Admin Secret:
    Name:   dev-domain-weblogic-credentials
  As Name:  admin-server
  As Port:  7001
  Cluster Startup:
    Cluster Name:   cluster-1
    Desired State:  RUNNING
    Env:
      Name:     JAVA_OPTIONS
      Value:    -Dweblogic.StdoutDebugEnabled=false
      Name:     USER_MEM_ARGS
      Value:    -Xms64m -Xmx256m 
    Replicas:   2
  Domain Name:  dev-domain
  Domain UID:   dev-domain
  Export T 3 Channels:
    T3Channel
  Image:              store/oracle/weblogic:12.2.1.3
  Image Pull Policy:  IfNotPresent
  Server Startup:
    Desired State:  RUNNING
    Env:
      Name:         JAVA_OPTIONS
      Value:        -Dweblogic.StdoutDebugEnabled=false
      Name:         USER_MEM_ARGS
      Value:        -Xms64m -Xmx256m 
    Node Port:      30701
    Server Name:    admin-server
  Startup Control:  AUTO
Events:             <none>
```
I can only see a single pod running in the namespace that is to contain the domain
```
[kkapoor@master dev-domain]$ kubectl get pods -n dev-domain
NAME                                            READY     STATUS    RESTARTS   AGE
dev-domain-cluster-1-traefik-6b75d4c77d-wv2wb   1/1       Running   0          2h
```

Not sure where to look as to why the servers did not start. Here's the domain-custom-resource.yaml file:
```
apiVersion: "weblogic.oracle/v1"
kind: Domain
metadata:
  name: dev-domain
  namespace: dev-domain
  labels:
    weblogic.domainUID: dev-domain
spec:
  # The domainUID must be unique across the entire Kubernetes Cluster.   Each WebLogic Domain must
  # have its own unique domainUID.  This does not have to be the same as the Domain Name.  It is allowed
  # to have multiple Domains with the same Domain Name, but they MUST have different domainUID's.
  # The domainUID is also used to identify the Persistent Volume that belongs to/with this Domain.
  domainUID: dev-domain
  # The WebLogic Domain Name
  domainName: dev-domain
  # The Operator currently does not support other images
  image: "store/oracle/weblogic:12.2.1.3"
  # imagePullPolicy defaults to "Always" if image version is :latest
  imagePullPolicy: "IfNotPresent"
  # Identify which Secret contains the WebLogic Admin credentials (note that there is an example of
  # how to create that Secret at the end of this file)
  adminSecret:
    name: dev-domain-weblogic-credentials
  # The name of the Admin Server
  asName: "admin-server"
  # The Admin Server's ListenPort
  asPort: 7001
  # startupControl legal values are "NONE", "ALL", "ADMIN", "SPECIFIED", or "AUTO"
  # This determines which WebLogic Servers the Operator will start up when it discovers this Domain
  # - "ALL" will start up all defined servers
  # - "ADMIN" will start up only the AdminServer (no managed servers will be started)
  # - "SPECIFIED" will start the AdminServer and then will look at the "serverStartup" and 
  #   "clusterStartup" entries below to work out which servers to start
  # - "AUTO" will start the servers as with "SPECIFIED", but then also start servers from
  #   other clusters up to the replicas count
  startupControl: "AUTO"
  # serverStartup is used to list the desired behavior for starting servers.  The Operator will
  # use this field only if startupControl is set to "SPECIFIED" or "AUTO".  You may provide a list of 
  # entries, each entry should contain the keys should below:
  serverStartup:
  # desiredState legal values are "RUNNING" or "ADMIN"
  # "RUNNING" means the listed server will be started up to "RUNNING" mode
  # "ADMIN" means the listed server will be start up to "ADMIN" mode
  - desiredState: "RUNNING"
    # the name of the server to apply these rules to
    serverName: "admin-server"
    # The Admin Server's NodePort
    nodePort: 30701
    # an (optional) list of environment variable to be set on the server
    env:
    - name: JAVA_OPTIONS
      value: "-Dweblogic.StdoutDebugEnabled=false"
    - name: USER_MEM_ARGS
      value: "-Xms64m -Xmx256m "
  # clusterStartup has the same structure as serverStartup, but it allows you to specify the name
  # of a cluster instead of an individual server.  If you use this entry, then the rules will be
  # applied to ALL servers that are members of the named clusters.
  clusterStartup:
  - desiredState: "RUNNING"
    clusterName: "cluster-1"
    replicas: 2
    env:
    - name: JAVA_OPTIONS
      value: "-Dweblogic.StdoutDebugEnabled=false"
    - name: USER_MEM_ARGS
      value: "-Xms64m -Xmx256m "
  # The number of managed servers to start from clusters not listed by clusterStartup
  # replicas: 1

  # Uncomment to export the T3Channel as a service
  exportT3Channels:
  - T3Channel
```

**Comment by rjeberhard** [comment]
Can you please verify that the operator is running and share it's log file?

kubectl logs deployment/weblogic-operator -n weblogic-operator > operator.log

... assuming the operator is deployed to the weblogic-operator namespace.

**Comment by karan-kapoor90** [comment]
[operator.log](https://github.com/oracle/weblogic-kubernetes-operator/files/1954111/operator.log)

Does have a 403 Forbidden on Config maps.. not sure what that means though.

**Comment by karan-kapoor90** [comment]
Looks like the security etc was not configured properly even though the domain creation job ran and completed successfully.

**Comment by alai8** [comment]
I noticed that there are "Access denied for service account" messages in the operator.log. Can you share the weblogic-operator-security.yaml file if you are still not able to get the servers to start?

**Comment by karan-kapoor90** [comment]
Here it is : 
```
#
# Namespace for WebLogic Operator
#
apiVersion: v1
kind: Namespace
metadata:
  name: weblogic-operator
---
#
# Service Account for WebLogic Operator
#
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: weblogic-operator
  name: weblogic-operator
---
#
# creating cluster roles
#
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: weblogic-operator-cluster-role
rules:
- apiGroups: [""]
  resources: ["namespaces", "persistentvolumes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["weblogic.oracle"]
  resources: ["domains"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["weblogic.oracle"]
  resources: ["domains/status"]
  verbs: ["update"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: weblogic-operator-cluster-role-nonresource
rules:
- nonResourceURLs: ["/version/*"]
  verbs: ["get"]
---
#
# creating cluster role-bindings
#
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: weblogic-operator-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: weblogic-operator
  namespace: weblogic-operator
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: weblogic-operator-cluster-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: weblogic-operator-operator-rolebinding-nonresource
subjects:
- kind: ServiceAccount
  name: weblogic-operator
  namespace: weblogic-operator
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: weblogic-operator-cluster-role-nonresource
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: weblogic-operator-operator-rolebinding-discovery
subjects:
- kind: ServiceAccount
  name: weblogic-operator
  namespace: weblogic-operator
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: system:discovery
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: weblogic-operator-operator-rolebinding-auth-delegator
subjects:
- kind: ServiceAccount
  name: weblogic-operator
  namespace: weblogic-operator
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io
---
#
# creating roles
#
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: weblogic-operator-namespace-role
rules:
- apiGroups: [""]
  resources: ["secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services", "configmaps", "pods", "jobs", "events"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: [""]
  resources: ["pods/logs"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["settings.k8s.io"]
  resources: ["podpresets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
- apiGroups: ["extensions"]
  resources: ["podsecuritypolicies", "networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
---
#
# creating role-bindings
#
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: weblogic-operator-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: weblogic-operator
  namespace: weblogic-operator
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: weblogic-operator-namespace-role
  apiGroup: ""
---
#
# creating role-bindings
#
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: weblogic-operator-rolebinding
  namespace: dev-domain
subjects:
- kind: ServiceAccount
  name: weblogic-operator
  namespace: weblogic-operator
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: weblogic-operator-namespace-role
  apiGroup: ""
---
#
# creating role-bindings
#
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: weblogic-operator-rolebinding
  namespace: test-domain
subjects:
- kind: ServiceAccount
  name: weblogic-operator
  namespace: weblogic-operator
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: weblogic-operator-namespace-role
  apiGroup: ""
---
#
# creating role-bindings
#
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: weblogic-operator-rolebinding
  namespace: prod-domain
subjects:
- kind: ServiceAccount
  name: weblogic-operator
  namespace: weblogic-operator
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: weblogic-operator-namespace-role
  apiGroup: ""
---
```
