### ISSUE TITLE
Weblogic SQLAuthenticator AuthenticationProvider delete all users and groups from DB on the creation domain step

### ISSUE THREAD

**Issue by khismatullinmax** [oracle/weblogic-kubernetes-operator#4303]
**Case:** We are using the Weblogic in k8s cluster with Weblogic k8s operator - https://oracle.github.io/weblogic-kubernetes-operator . We want to store and manage (create, modify, reset password) our Weblogic users and groups permanently in the external AuthenticationProvider, for example SQLAuthenticator. We followed the guideline - https://www.oracle.com/webfolder/technetwork/tutorials/obe/fmw/wls/12c/12_2_1/sqlauthenticator/sqlauthenticator.html#summary. 
It works fine if users were inserted to DB after the domain creation with Weblogic Deploy Tool. 

Issue: SQLAuthenticator Authentication Provider delete all users and groups from DB only on the domain creation step with aux images, and we found it by SQL logs (see attachments). If we will recreate admin or manage servers pods - this action doesn't delete the data from DB.

**SQL logs:**
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/khismama/AppData/Local/Packages/oice_16_974fa576_32c1d314_3c2/AC/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/khismama/AppData/Local/Packages/oice_16_974fa576_32c1d314_3c2/AC/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

SQL_FULLTEXT | MODULE
-- | --
DELETE   FROM GROUPMEMBERS | JDBC Thin Client
INSERT   INTO GROUPS (G_NAME, G_DESCRIPTION) values ('Deployers', 'Deployers can view   all resource attributes and deploy applications.') | JDBC Thin Client
DELETE   FROM GROUPS | JDBC Thin Client
INSERT   INTO GROUPS (G_NAME, G_DESCRIPTION) values ('CrossDomainConnectors',   'CrossDomainConnectors can make inter-domain calls from foreign domains.') | JDBC Thin Client
INSERT   INTO GROUPS (G_NAME, G_DESCRIPTION) values ('OracleSystemGroup', 'Oracle   application software system group.') | JDBC Thin Client
INSERT   INTO GROUPS (G_NAME, G_DESCRIPTION) values ('Monitors', 'Monitors can view   and modify all resource attributes and perform operations not restricted by   roles.') | JDBC Thin Client
INSERT   INTO USERS (U_NAME, U_PASSWORD, U_DESCRIPTION) values ('LCMUser',   '***', 'This is the default   service account for WebLogic Server Lifecycle Manager configuration   updates.') | JDBC Thin Client
INSERT   INTO GROUPS (G_NAME, G_DESCRIPTION) values ('AdminChannelUsers',   'AdminChannelUsers can access the admin channel.') | JDBC Thin Client
INSERT   INTO GROUPS (G_NAME, G_DESCRIPTION) values ('AppTesters', 'AppTesters   group.') | JDBC Thin Client
INSERT   INTO GROUPS (G_NAME, G_DESCRIPTION) values ('Operators', 'Operators can view   and modify all resource attributes and perform server lifecycle operations.') | JDBC Thin Client
INSERT   INTO GROUPS (G_NAME, G_DESCRIPTION) values ('Administrators', 'Administrators   can view and modify all resource attributes and start and stop servers.') | JDBC Thin Client
DELETE   FROM USERS | JDBC Thin Client

</body>

</html>

**Model:**
```
---
topology:
  Security:
    Group: {}
    User: {}
  SecurityConfiguration:
    Realm:
      myrealm:
        RoleMapper:
          XACMLRoleMapper:
            XACMLRoleMapper: {}
        AuthenticationProvider:
          DefaultAuthenticator:
            DefaultAuthenticator:
              ControlFlag: "SUFFICIENT"
          UMSQLAuthenticator:
            SQLAuthenticator:
              DataSourceName: "SQLAuthenticatorDataSource"
              ControlFlag: "SUFFICIENT"
resources:
  JDBCSystemResource:
    SQLAuthenticatorDataSource:
      Target: "admin-server,@@ENV:WEBLO_CLUSTER_NAME@@"
      JdbcResource:
        JDBCDataSourceParams:
          JNDIName: "jdbc/SQLAuthenticatorDataSource"
          GlobalTransactionsProtocol: "TwoPhaseCommit"
          RowPrefetch: true
          RowPrefetchSize: 48
          StreamChunkSize: 16384
        JDBCDriverParams:
          Properties:
            user:
              Value: "SQLAUTHENTICATOR"
          DriverName: "oracle.jdbc.replay.OracleXADataSourceImpl"
          URL: "jdbc:oracle:thin:@//...."
          PasswordEncrypted: "password"
        JDBCConnectionPoolParams:
          InitialCapacity: 1
          MaxCapacity: 10
          CapacityIncrement: 1
          ShrinkFrequencySeconds: 120
          TestConnectionsOnReserve: true
          TestTableName: "SQL SELECT * FROM DUAL"
          StatementCacheSize: 10
          SecondsToTrustAnIdlePoolConnection: 0
          ConnectionReserveTimeoutSeconds: 0
        JDBCXAParams:
          XaSetTransactionTimeout: true
          XaTransactionTimeout: 1500
        JDBCOracleParams:
          FanEnabled: false
appDeployments:
  Library: {}
  Application: {}
```

Our guess is that it happened because in our weblogic-operator-model we don't have any users and groups to be created by default in Weblogic (because they will be created only in DefaultAuthenticator). 

```
topology:
  Security:
    Group: {}
    User: {}
```

**Question:** Is this issue expected? Could you provide us the justification why it happened and can we disable it? We want to store our users and groups permanently in DB without the deletion and use full lifecycle management of the users with SQLAuthenticator.
