### ISSUE TITLE
`securityContext` for the container `weblogic-server`

### ISSUE THREAD

**Issue by gregoan** [oracle/weblogic-kubernetes-operator#4894]
Hello,

In order to remain coherent between `initContainer` and `container`, could it be possible to offer the capability to define `securityContext` for the container `weblogic-server` ?

Thanks.

**Comment by rjeberhard** [comment]
The `securityContext` for the `weblogic-server` container is controlled by the `domain.spec.serverPod.containerSecurityContext` field.

**Comment by gregoan** [comment]
Hello @rjeberhard 
We are using the following podSecurityContext definition:

```
  serverPod:

    podSecurityContext:
      fsGroup: 1
      seccompProfile:
        type: RuntimeDefault

      # Is the ID of the group so "bin"
      supplementalGroups:
        - 1

      runAsNonRoot: true
      runAsUser: 1000
```

Here is an example of container we are using:

```
    containers:
    - name: xxx
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
```

The elements `privileged`, `allowPrivilegeEscalation` and `capabilities` are specific to container and not to pod.
We dont' have access to the definition of `weblogic-server` container so what I'm asking if it could be possible to have the capability to define the `securityContext` element for the container  `weblogic-server` in order to increase a bit the security.
